version: '3'

services:
  database:
    container_name: craft-test-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  php:
    container_name: craft-test-php
    # image: dylansm/php_fpm_alpine
    # local image
    image: php-fpm
    links:
      - database
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .:/usr/share/nginx:rw
      - ./etc/php7/conf.d/xdebug.ini:/etc/php7/conf.d/xdebug.ini:ro
      - ./etc/php7/php-fpm.conf:/etc/php7/php-fpm.conf:ro
      - ./etc/php7/php-fpm.d/www.conf:/etc/php7/php-fpm.d/www.conf:ro

  web:
    container_name: craft-test
    environment:
      - VIRTUAL_HOST=craft-test.dev
    image: nginx:alpine
    links:
      - php
    ports:
      - "3001:3001"
    volumes:
    - ./web:/usr/share/nginx/web
    - ./etc/nginx/conf.d/:/etc/nginx/conf.d

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  postgres_data:
    driver: local
